const express = require("express")
const router = express.Router()
const verifyJWT = require("../middleware/verifyJWT")
const usersController = require("../controllers/usersController")
router.delete("/:id",verifyJWT,usersController.deleteUsers)
router.get("/:_id",verifyJWT, usersController.getUserById)
router.get("/",verifyJWT, usersController.getAllUsers)
router.put("/:id",verifyJWT,usersController.updateUser)
router.get("/getByRoles/:id",verifyJWT, usersController.getUserByRoles)
module.exports = router